# Generated by Django 2.0.13 on 2019-03-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
